### ISSUE TITLE
Difference between this and google/fonts?

### ISSUE THREAD

**Issue by samatjain** [w0ng/googlefontdirectory#15]
Google just created a new fonts repository, with a goal _very_ similar to this one:

https://github.com/google/fonts

The size between this repo and Google's is nearly identical; do you know the differences between theirs? Will this repository continue to be updated?

**Comment by AC10** [comment]
Google's repo is only 4 days old.. 
This repo is a few years old, the initial commit was 4 Aug 2012

But otherwise, there's no difference. Both repos provides the ``` .ttf ``` files for every font, and a ``` METADATA.json ``` with the author etc.

**Comment by surjithctly** [comment]
@w0ng Thanks for sharing, You could also make a popular google fonts repo, < 50 mb, That would be useful.

Also, The current download size is 198 MB, But mentioned as 100 MB in Readme, could be better if you put exact size to avoid ambiguity.

**Comment by davelab6** [comment]
The code.google.com hg repo will eventually go away, as the whole google code hosting site is being shut down this year; the future home is that git repo

**Comment by joemaller** [comment]
I can't believe Google nuked the project history. I first mirrored that in 2010, so there's at least 5 years of commits and development they just decided to willfully erase.

**Comment by surjithctly** [comment]
Official Github Repo is Live Now? https://github.com/google/fonts

**Comment by w0ng** [comment]
Please use the official repo: https://github.com/google/fonts

The original intention of this repo was to serve as a workaround for:
https://code.google.com/p/googlefontdirectory/issues/detail?id=2

It was purely a clone of Google's hg repo to serve the binary files without the source files.
Now that there is an official Google binary fonts repo, we don't need a workaround anymore!
I've deleted all the contents here, since it serves no benefit to anyone.
Everyone should start following/starring https://github.com/google/fonts instead.

**Comment by davelab6** [comment]
Why does it matter?
